server:
  port: 8083
spring:
  application:
    name: user-api
eureka:
  instance:
    instance-id: user-api-8083
    prefer-ip-address: true # 访问路径可以显示 IP
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/  # 注册中心访问地址