server:
  port: 8081
spring:
  application:
    name: user-api
eureka:
  instance:
    instance-id: user-api-8081
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka01:9001/eureka/,http://eureka02:9002/eureka/,http://eureka03:9003/eureka/